spring:
  thymeleaf:
    mode: LEGACYHTML5
    cache: true
  datasource:
    url: jdbc:mysql://localhost:3306/world?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 594682797
    driver-class-name: com.mysql.jdbc.Driver
  data:
    solr:
      zk-host: 192.168.13.129:2181
mybatis:
  mapper-locations: mapper/*.xml
sensor:
  port: 8080
  dataLength: 27
server:
  port: 8080